// auth types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

// post types
export const RECENT_POSTS = 'RECENT_POSTS';
export const CLEAR_RECENT_POSTS = 'CLEAR_RECENT_POSTS';
export const PROFILE_POSTS = 'PROFILE_POSTS';
export const USER_PROFILE_DETAILS = 'USER_PROFILE_DETAILS';

// chat types
export const SOCKET_CONNECTION = 'SOCKET_CONNECTION';
export const ONLINE_USERS = 'ONLINE_USERS';
export const CLEAR_SOCKET_STATE = 'CLEAR_SOCKET_STATE';
